"""Assisted publisher (default): prepares approved drafts for manual posting.

Does three human-friendly things, all optional via config.publishing:
  * writes a ready-to-post export file (caption + hashtags + media path)
  * copies the caption+hashtags to the clipboard (macOS pbcopy via pyperclip)
  * optionally opens the platform's web composer in your browser

It explicitly does NOT post anything. You copy/paste and hit publish yourself.
"""
from __future__ import annotations

import datetime as dt
import webbrowser
from pathlib import Path

from trendengine.config import PROJECT_ROOT, Config
from trendengine.db.models import Draft
from trendengine.logging_setup import get_logger
from trendengine.publishers.base import Publisher, PublishResult

log = get_logger(__name__)

# Web composer URLs to open on prepare (best-effort convenience).
COMPOSER_URLS = {
    "instagram": "https://www.instagram.com/",
    "tiktok": "https://www.tiktok.com/upload",
    "x": "https://x.com/compose/post",
    "linkedin": "https://www.linkedin.com/feed/?shareActive=true",
}


class AssistedPublisher(Publisher):
    name = "assisted"

    def prepare(self, draft: Draft) -> PublishResult:
        export_dir = PROJECT_ROOT / self.settings.get("export_dir", "exports")
        export_dir.mkdir(parents=True, exist_ok=True)

        caption = draft.caption or ""
        hashtags = draft.hashtags or ""
        full_text = f"{caption}\n\n{hashtags}".strip()

        stamp = dt.datetime.now().strftime("%Y%m%d-%H%M%S")
        slug = _slug(draft.topic) or "post"
        export_path = export_dir / f"{stamp}_{draft.id}_{slug}.md"
        export_path.write_text(_render_export(draft, full_text), encoding="utf-8")
        log.info("Exported draft #%d -> %s", draft.id, export_path)

        clip_ok = True
        if self.settings.get("copy_to_clipboard", True):
            clip_ok = _copy_to_clipboard(full_text)

        if self.settings.get("open_browser", False):
            url = COMPOSER_URLS.get(draft.platform)
            if url:
                try:
                    webbrowser.open(url)
                except Exception as exc:  # noqa: BLE001
                    log.warning("Could not open browser: %s", exc)

        msg = f"Prepared. Export saved to {export_path.name}."
        if self.settings.get("copy_to_clipboard", True):
            msg += " Caption copied to clipboard." if clip_ok else \
                   " (clipboard copy unavailable in this environment)"
        return PublishResult(ok=True, message=msg, export_path=str(export_path))


def _render_export(draft: Draft, full_text: str) -> str:
    media = draft.media_path or "(none — attach your image/video before posting)"
    return f"""# Ready to post — {draft.platform}

**Topic:** {draft.topic}
**Draft ID:** {draft.id}
**Why now:** {draft.rationale or "(n/a)"}

---

## Caption + hashtags (copy this)

{full_text}

---

## Media
{media}

## Evidence
{draft.source_summary or "(n/a)"}

_Generated by {draft.llm_provider}:{draft.llm_model}. Nothing is posted automatically._
"""


def _copy_to_clipboard(text: str) -> bool:
    try:
        import pyperclip
        pyperclip.copy(text)
        return True
    except Exception as exc:  # noqa: BLE001 - headless env has no clipboard
        log.info("Clipboard copy skipped: %s", exc)
        return False


def _slug(text: str) -> str:
    keep = [c.lower() if c.isalnum() else "-" for c in (text or "")]
    slug = "".join(keep).strip("-")
    while "--" in slug:
        slug = slug.replace("--", "-")
    return slug[:40]
